---

############################################################
#  Enble Config Logging
############################################################

- name: Archive logging config
  #check_mode: "{{ checkmode }}"
  ios_config:
    lines:
      - logging enable
      - logging size 1000
      - hidekeys
    parents:
      - archive
      - log config
    defaults: no
  tags: archive


############################################################
#  Confirm only authorized system users exist
############################################################

- name: Create local users
  #check_mode: "{{ checkmode }}"
  ios_user:
    aggregate: "{{local_users_full}}"
    state: present
    update_password: on_create
    purge: yes


############################################################
#  System Configuration
############################################################

- name: System settings
  #check_mode: "{{ checkmode }}"
  cisco.ios.ios_system:
    domain_name: "{{ domain_name }}"
    lookup_enabled: no
    

#############################################################
# NTP Configuration
#############################################################

- name: Set NTP
  #check_mode: "{{ checkmode }}"
  loop: "{{ ntp_servers }}"
  cisco.ios.ios_config:
    lines:
      - ntp server {{ item }}


#############################################################
# VTY Configuration
#############################################################
- name: Configure VTY and console
  #check_mode: "{{ checkmode }}"
  loop: 
    - line vty 0 4
    - line vty 5 15
    - line con 0
  cisco.ios.ios_config:
    lines:
      - exec-timeout 120 0
    parents: "{{ item }}"


#############################################################
# Catchall Configuration
#############################################################

- name: Check catchall config items
  #check_mode: "{{ checkmode }}"
  cisco.ios.ios_config:
    lines:
      - clock timezone PST -8 0
      - clock summer-time PDT recurring
      - service timestamps debug datetime msec localtime show-timezone
      - service timestamps log datetime msec localtime show-timezone
      - netconf-yang
      - restconf
      - spanning-tree extend system-id
      - ip http server
      - ip http authentication local
      - ip http secure-server
      - ip ssh version 2
    #backup: yes
