---

############################################################
#  System Configuration
############################################################

- name: System settings
  check_mode: "{{ checkmode }}"
  cisco.ios.ios_system:
    domain_name: "{{ domain_name }}"
    lookup_enabled: no
    domain_search: "{{ domain_search }}"

#############################################################
# Catchall Configuration
#############################################################

- name: Check catchall config items
  check_mode: "{{ checkmode }}"
  cisco.ios.ios_config:
    lines:
      - clock timezone PST -8 0
      - clock summer-time PDT recurring
      - service timestamps debug datetime msec localtime show-timezone
      - service timestamps log datetime msec localtime show-timezone



