---

############################################################
#  System Configuration
############################################################

- name: System settings
  #check_mode: "{{ checkmode }}"
  cisco.nxos.nxos_system:
    domain_name: "{{ domain_name }}"
    domain_lookup: no

############################################################
#  Feature Configuration
############################################################

- name: Feature settings
  #check_mode: "{{ checkmode }}"
  loop: "{{ features }}"
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"

#############################################################
# NTP Configuration
#############################################################

- name: Set NTP
  #check_mode: "{{ checkmode }}"
  loop: "{{ ntp_servers }}"
  cisco.nxos.nxos_config:
    lines:
      - ntp server {{ item }} use-vrf default

#############################################################
# Catchall Configuration
#############################################################

- name: Check catchall config items
  #check_mode: "{{ checkmode }}"
  cisco.nxos.nxos_config:
    lines:
      - clock timezone PST -8 0
      - clock summer-time PDT 2 Sun Mar 02:00 1 Sun Nov 02:00 60
      - logging timestamp milliseconds
